name: Python GitOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Python Code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        # 登入帳號依然可用 actor 變數
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 【新增步驟】在 Linux 雲端機器中，把專案名稱轉成全小寫存起來
    - name: Downcase repo name
      run: |
        echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # 這裡改用我們剛剛轉換好、保證全小寫的 REPO_LC 變數
        tags: |
          ghcr.io/${{ env.REPO_LC }}:latest
          ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}

    - name: Checkout K8s Manifest Repo
      uses: actions/checkout@v4
      with:
        repository: '${{ github.actor }}/k8s-gitops-manifests' 
        token: ${{ secrets.G_TOKEN }}
        path: k8s-manifests

    - name: Update Kubernetes YAML Image Tag
      run: |
        cd k8s-manifests
        # 這裡也要同步改用全小寫的映像檔路徑
        sed -i "s|image:.*|image: ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}|g" app.yaml
        sed -i "s|containerPort:.*|containerPort: 5000|g" app.yaml
        sed -i "s|targetPort:.*|targetPort: 5000|g" app.yaml
        cat app.yaml

    - name: Commit and Push Changes back to K8s Repo
      run: |
        cd k8s-manifests
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add app.yaml
        git commit -m "🤖 自動化 CI 升級：部署最新的 Python 映像檔 [commit ${{ github.sha }}]"
        git push origin main
